name: test workflow_run

on:
  workflow_run:
    workflows: [test on_push_tags]
    types:
      - completed

permissions:
  contents: read

jobs:
  test-job:
    name: "Run test job"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          ORIGINAL_REF=${{ github.event.workflow_run.head_branch }}
          
          if git show-ref -q --verify refs/tags/$ORIGINAL_REF
          then
            echo "it's a tag"
          fi
          
          echo $ORIGINAL_REF
          echo $GITHUB_CONTEXT
